version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_oauth
    environment:
      POSTGRES_USER: oauth
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: oauth
    ports:
      - "5442:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M

volumes:
  postgres_data:
